version: '3'
services:
  app:
    container_name: happy2-app
    build: app
    hostname: happy2
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8000:8000"
    external_links:
      - happy2-db:db
    depends_on:
      - db
  db:
    container_name: happy2-db
    # build: db
    hostname: db
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
      - "./db/conf.d:/etc/mysql/conf.d"
      - "./db/datadir:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=happy2
